### ISSUE TITLE
Build failure on BSD

### ISSUE THREAD

**Issue by chrisduerr** [Smithay/client-toolkit#41]
It looks like the wayland client toolkit fails to build on OpenBSD 6.4. This has been reported to Alacritty here: https://github.com/jwilm/alacritty/issues/1784.

The relevant error output is the following:
```
   Compiling smithay-client-toolkit v0.4.1
error[E0432]: unresolved import `nix::sys::memfd`
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.4.1/src/utils/mempool.rs
  |
4 | use nix::sys::memfd;
  |     ^^^^^^^^^^^^^^^ no `memfd` in `sys`

error: aborting due to previous error
```

I'd propose a breaking change to make this crate empty by default if the build target is not Linux, this way it should always build on all systems. Note that other crates like winapi do something similar.

**Comment by vberger** [comment]
I see several potential fixes for that:

- winit could disable the wayland backend on *BSD
- SCTK / wayland-rs could be made a noop on *BSD
- my personal preference, as apparently there is [a potentiality that wayland could work on FreeBSD](https://www.phoronix.com/scan.php?page=news_item&px=FreeBSD-Wayland-Availability), would be to make the crate BSD compatible

I believe it should not be too much work, as the mempool module is a rather small thing to port, though I have no experience with any of the *BSD

**Comment by chrisduerr** [comment]
All of these seem fairly reasonable, however making it work on BSD would also only work if it would actually build. So either way there's a problem which needs to be resolved.

Disabling it in winit/wayland-rs might also be a problem, however I feel like solving this problem at the root would have the biggest positive impact on the users, otherwise it might happen N times again.

**Comment by vberger** [comment]
However, winit has a lot of code using SCTK's API, so it's not possible to make SCTK into a noop crate without also disabling it in winit (or winit won't compile any more)... which kind of makes it rather pointless to make SCTK into a noop crate in the first place, wouldn't it?

**Comment by vberger** [comment]
So, the fix was actually rather simple, and I believe with #42 that should be fixed. The hardest part was actually setting up the scripts to test on FreeBSD :smile:

**Comment by thendiscard** [comment]
@vberger I've run a `cargo test` and `cargo build --release` on OpenBSD and everything seems fine to me, there are some warnings but the build is successful. If you want me to run any other tests let me know. Thank you for your quick reply and fix !

```bash
user ~/ALACRITTY/client-toolkit $ rustc -Vv
rustc 1.30.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-openbsd
release: 1.30.1
LLVM version: 6.0

user ~/ALACRITTY/client-toolkit $ git log -n 1
commit 38a93b0bc5196d25032cd5965aeef35a0cc01710 (HEAD -> master, tag: v0.4.2, origin/master, origin/HEAD)
Author: Victor Berger <victor.berger@m4x.org>
Date:   Wed Nov 14 23:15:02 2018 +0100

    version 0.4.2
~
~

user ~/ALACRITTY/client-toolkit $ cargo test
    Updating crates.io index
   Compiling cc v1.0.25
   Compiling cfg-if v0.1.6
   Compiling nodrop v0.1.13
   Compiling nix v0.11.0
   Compiling lazy_static v1.2.0
   Compiling scopeguard v0.3.3
   Compiling num-traits v0.2.6
   Compiling memoffset v0.2.1
   Compiling xml-rs v0.8.0
   Compiling proc-macro2 v0.4.23
   Compiling libc v0.2.43
   Compiling bitflags v1.0.4
   Compiling unicode-xid v0.1.0
   Compiling void v1.0.2
   Compiling rayon-core v1.4.1
   Compiling num-integer v0.1.39
   Compiling byteorder v1.2.7
   Compiling rayon v1.0.3
   Compiling num-iter v0.1.37
   Compiling adler32 v1.0.3
   Compiling either v1.5.0
   Compiling rand_core v0.3.0
   Compiling num-derive v0.2.3
   Compiling same-file v1.0.4
   Compiling downcast-rs v1.0.3
   Compiling xdg v2.1.0
   Compiling color_quant v1.0.1
   Compiling lzw v0.10.0
   Compiling scoped_threadpool v0.1.9
   Compiling crossbeam-utils v0.2.2
   Compiling arrayvec v0.4.7
   Compiling inflate v0.4.3
   Compiling num_cpus v1.8.0
   Compiling memmap v0.6.2
   Compiling stb_truetype v0.2.4
   Compiling deflate v0.7.19
   Compiling walkdir v2.2.7
   Compiling rand_core v0.2.2
   Compiling gif v0.10.1
   Compiling crossbeam-epoch v0.3.1
   Compiling wayland-scanner v0.21.4
   Compiling libloading v0.5.0
   Compiling rand v0.5.5
   Compiling crossbeam-deque v0.2.0
   Compiling dlib v0.4.1
   Compiling wayland-sys v0.21.4
   Compiling quote v0.6.10
   Compiling ordered-float v1.0.1
   Compiling approx v0.3.0
   Compiling line_drawing v0.7.0
   Compiling syn v0.15.20
   Compiling rusttype v0.7.2
   Compiling wayland-client v0.21.4
   Compiling wayland-protocols v0.21.4
   Compiling num-rational v0.1.42
   Compiling png v0.12.0
   Compiling andrew v0.1.4
   Compiling jpeg-decoder v0.1.15
   Compiling wayland-commons v0.21.4
   Compiling image v0.19.0
   Compiling smithay-client-toolkit v0.4.2 (/home/user/ALACRITTY/client-toolkit)
warning: unused import: `std::ffi::CStr`
 --> src/utils/mempool.rs:9:5
  |
9 | use std::ffi::CStr;
  |     ^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: missing documentation for crate
  --> src/lib.rs:1:1
   |
1  | / #![warn(missing_docs)]
2  | |
3  | | #[macro_use]
4  | | extern crate bitflags;
...  |
34 | |
35 | | pub use env::{Environment, Shell};
   | |__________________________________^
   |
note: lint level defined here
  --> src/lib.rs:1:9
   |
1  | #![warn(missing_docs)]
   |         ^^^^^^^^^^^^

warning: missing documentation for a module
  --> src/lib.rs:31:1
   |
31 | pub mod window;
   | ^^^^^^^^^^^^^^^

warning: unused import: `std::ffi::CStr`
 --> src/utils/mempool.rs:9:5
  |
9 | use std::ffi::CStr;
  |     ^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1m 04s
     Running target/debug/deps/smithay_client_toolkit-f57bdef841aba384

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests smithay-client-toolkit

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

user ~/ALACRITTY/client-toolkit $ cargo build --release
   Compiling cc v1.0.25
   Compiling nix v0.11.0
   Compiling xml-rs v0.8.0
   Compiling num-traits v0.2.6
   Compiling lazy_static v1.2.0
   Compiling libc v0.2.43
   Compiling bitflags v1.0.4
   Compiling void v1.0.2
   Compiling cfg-if v0.1.6
   Compiling nodrop v0.1.13
   Compiling byteorder v1.2.7
   Compiling downcast-rs v1.0.3
   Compiling same-file v1.0.4
   Compiling rand_core v0.3.0
   Compiling xdg v2.1.0
   Compiling arrayvec v0.4.7
   Compiling walkdir v2.2.7
   Compiling stb_truetype v0.2.4
   Compiling rand_core v0.2.2
   Compiling memmap v0.6.2
   Compiling rand v0.5.5
   Compiling ordered-float v1.0.1
   Compiling approx v0.3.0
   Compiling line_drawing v0.7.0
   Compiling rusttype v0.7.2
   Compiling wayland-scanner v0.21.4
   Compiling andrew v0.1.4
   Compiling libloading v0.5.0
   Compiling wayland-client v0.21.4
   Compiling wayland-protocols v0.21.4
   Compiling dlib v0.4.1
   Compiling wayland-sys v0.21.4
   Compiling wayland-commons v0.21.4
   Compiling smithay-client-toolkit v0.4.2 (/home/user/ALACRITTY/client-toolkit)
warning: unused import: `std::ffi::CStr`
 --> src/utils/mempool.rs:9:5
  |
9 | use std::ffi::CStr;
  |     ^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: missing documentation for crate
  --> src/lib.rs:1:1
   |
1  | / #![warn(missing_docs)]
2  | |
3  | | #[macro_use]
4  | | extern crate bitflags;
...  |
34 | |
35 | | pub use env::{Environment, Shell};
   | |__________________________________^
   |
note: lint level defined here
  --> src/lib.rs:1:9
   |
1  | #![warn(missing_docs)]
   |         ^^^^^^^^^^^^

warning: missing documentation for a module
  --> src/lib.rs:31:1
   |
31 | pub mod window;
   | ^^^^^^^^^^^^^^^

    Finished release [optimized] target(s) in 1m 11s
```

**Comment by vberger** [comment]
Perfect, thanks for the feedback!

Right now, I'm only testing that the libs compile on FreeBSD, with the goal of them "just being ready" if/when wayland becomes more present in the BSD ecosystem, or maybe with minor bugfixes for everything to run smoothly.
